### ISSUE TITLE
pg:connect: Backend error: FATAL:  unsupported frontend protocol 1.0: server supports 2.0 to 3.0

### ISSUE THREAD

**Issue by gnusupport** [anse1/emacs-libpq#7]
Since PostgreSQL version 10.1 the protocol version 1.0 has been removed, and such is used by pg.el and each package, just as this one.

See the change here:
https://www.postgresql.org/docs/current/static/release-10.html

As protocol 1.0 has been dropped, the pg.el on which this package depends does not work any more with the PostgreSQL latest version 10.1

If you can do anything to handle this problem, please do, as of now, all PostgreSQL programs with Emacs are broken on my side.

**Comment by anse1** [comment]
notifications@github.com writes:

> Since PostgreSQL version 10.1 the protocol version 1.0 has been
> removed, and such is used by pg.el and each package, just as this one.

This is not the repository for pg.el.  It's a C implementation using the
emacs-module interface based on libpq.  The function from the subject
you are calling is not part of pq.

> As protocol 1.0 has been dropped, the pg.el on which this package
> depends does not work any more with the PostgreSQL latest version 10.1

This module (pq) does not depend on pg.el either.

> If you can do anything to handle this problem, please do, as of now,
> all PostgreSQL programs with Emacs are broken on my side.

pq uses whatever protocol version the libpq you build it against uses,
so it will just work with PostgreSQL 10.1 unless you link it against a
libpq version from the last millenium.

regards,
Andreas
